services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      dockerfile: Dockerfile
      context: "./frontend"
    depends_on:
      - nestjs
    networks:
      - my_network
    volumes:
      - /frontend/node_modules
      - ./frontend:/app
    ports:
      - "3001:3000"
    command: sh -c "npm ci && npm run start"

  nestjs:
    container_name: nestjs
    image: nestjs
    build:
      dockerfile: Dockerfile
      context: "./backend"
    env_file:
      - .env
    networks:
      - my_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./secrets:/usr/src/app/secrets
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "cd ./backend && npm ci && npm run start:dev"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16
    networks:
      - my_network
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    networks:
      - my_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

networks:
  my_network:
    driver: bridge

volumes:
  pg-data:
