/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Auth
 * The NestJS Auth API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class QueueApi extends runtime.BaseAPI {

    /**
     * Get the current queue status
     */
    async queueControllerGetQueueStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/queue/status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get the current queue status
     */
    async queueControllerGetQueueStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.queueControllerGetQueueStatusRaw(initOverrides);
    }

    /**
     * Join the queue
     */
    async queueControllerJoinQueueRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/queue/join`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Join the queue
     */
    async queueControllerJoinQueue(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.queueControllerJoinQueueRaw(initOverrides);
    }

}
