/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Auth
 * The NestJS Auth API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBlockedDto
 */
export interface CreateBlockedDto {
    /**
     * blocked_time
     * @type {Date}
     * @memberof CreateBlockedDto
     */
    blockedTime: Date;
}

/**
 * Check if a given object implements the CreateBlockedDto interface.
 */
export function instanceOfCreateBlockedDto(value: object): value is CreateBlockedDto {
    if (!('blockedTime' in value) || value['blockedTime'] === undefined) return false;
    return true;
}

export function CreateBlockedDtoFromJSON(json: any): CreateBlockedDto {
    return CreateBlockedDtoFromJSONTyped(json, false);
}

export function CreateBlockedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBlockedDto {
    if (json == null) {
        return json;
    }
    return {
        
        'blockedTime': (new Date(json['blocked_time'])),
    };
}

export function CreateBlockedDtoToJSON(json: any): CreateBlockedDto {
    return CreateBlockedDtoToJSONTyped(json, false);
}

export function CreateBlockedDtoToJSONTyped(value?: CreateBlockedDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blocked_time': ((value['blockedTime']).toISOString()),
    };
}

