/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Auth
 * The NestJS Auth API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGameDto
 */
export interface CreateGameDto {
    /**
     * Player 1 user ID
     * @type {number}
     * @memberof CreateGameDto
     */
    player1UserId: number;
    /**
     * Player 2 user ID
     * @type {number}
     * @memberof CreateGameDto
     */
    player2UserId: number;
    /**
     * Winner user ID
     * @type {number}
     * @memberof CreateGameDto
     */
    winnerUserId: number;
    /**
     * Is it a ladder game?
     * @type {boolean}
     * @memberof CreateGameDto
     */
    isLadderGame: boolean;
}

/**
 * Check if a given object implements the CreateGameDto interface.
 */
export function instanceOfCreateGameDto(value: object): value is CreateGameDto {
    if (!('player1UserId' in value) || value['player1UserId'] === undefined) return false;
    if (!('player2UserId' in value) || value['player2UserId'] === undefined) return false;
    if (!('winnerUserId' in value) || value['winnerUserId'] === undefined) return false;
    if (!('isLadderGame' in value) || value['isLadderGame'] === undefined) return false;
    return true;
}

export function CreateGameDtoFromJSON(json: any): CreateGameDto {
    return CreateGameDtoFromJSONTyped(json, false);
}

export function CreateGameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGameDto {
    if (json == null) {
        return json;
    }
    return {
        
        'player1UserId': json['player1_user_id'],
        'player2UserId': json['player2_user_id'],
        'winnerUserId': json['winner_user_id'],
        'isLadderGame': json['is_ladder_game'],
    };
}

export function CreateGameDtoToJSON(json: any): CreateGameDto {
    return CreateGameDtoToJSONTyped(json, false);
}

export function CreateGameDtoToJSONTyped(value?: CreateGameDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player1_user_id': value['player1UserId'],
        'player2_user_id': value['player2UserId'],
        'winner_user_id': value['winnerUserId'],
        'is_ladder_game': value['isLadderGame'],
    };
}

