/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Auth
 * The NestJS Auth API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
    /**
     * User avatar
     * @type {object}
     * @memberof CreateUserDto
     */
    avatar: object;
    /**
     * User nickname
     * @type {string}
     * @memberof CreateUserDto
     */
    nickname: string;
    /**
     * enable two factor authentication
     * @type {boolean}
     * @memberof CreateUserDto
     */
    enableTwoFactor: boolean;
    /**
     * Second authentication check
     * @type {boolean}
     * @memberof CreateUserDto
     */
    isSecondAuthDone: boolean;
    /**
     * Second authentication code
     * @type {number}
     * @memberof CreateUserDto
     */
    secondAuthCode: number;
    /**
     * email address
     * @type {string}
     * @memberof CreateUserDto
     */
    email: string;
    /**
     * Ladder level
     * @type {number}
     * @memberof CreateUserDto
     */
    ladderLevel: number;
    /**
     * User status
     * @type {string}
     * @memberof CreateUserDto
     */
    userStatus: string;
}

/**
 * Check if a given object implements the CreateUserDto interface.
 */
export function instanceOfCreateUserDto(value: object): value is CreateUserDto {
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('enableTwoFactor' in value) || value['enableTwoFactor'] === undefined) return false;
    if (!('isSecondAuthDone' in value) || value['isSecondAuthDone'] === undefined) return false;
    if (!('secondAuthCode' in value) || value['secondAuthCode'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('ladderLevel' in value) || value['ladderLevel'] === undefined) return false;
    if (!('userStatus' in value) || value['userStatus'] === undefined) return false;
    return true;
}

export function CreateUserDtoFromJSON(json: any): CreateUserDto {
    return CreateUserDtoFromJSONTyped(json, false);
}

export function CreateUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'],
        'nickname': json['nickname'],
        'enableTwoFactor': json['enable_two_factor'],
        'isSecondAuthDone': json['is_second_auth_done'],
        'secondAuthCode': json['second_auth_code'],
        'email': json['email'],
        'ladderLevel': json['ladder_level'],
        'userStatus': json['user_status'],
    };
}

export function CreateUserDtoToJSON(json: any): CreateUserDto {
    return CreateUserDtoToJSONTyped(json, false);
}

export function CreateUserDtoToJSONTyped(value?: CreateUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar': value['avatar'],
        'nickname': value['nickname'],
        'enable_two_factor': value['enableTwoFactor'],
        'is_second_auth_done': value['isSecondAuthDone'],
        'second_auth_code': value['secondAuthCode'],
        'email': value['email'],
        'ladder_level': value['ladderLevel'],
        'user_status': value['userStatus'],
    };
}

