/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Auth
 * The NestJS Auth API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAchievementDto
 */
export interface CreateAchievementDto {
    /**
     * 
     * @type {number}
     * @memberof CreateAchievementDto
     */
    userId: number;
}

/**
 * Check if a given object implements the CreateAchievementDto interface.
 */
export function instanceOfCreateAchievementDto(value: object): value is CreateAchievementDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CreateAchievementDtoFromJSON(json: any): CreateAchievementDto {
    return CreateAchievementDtoFromJSONTyped(json, false);
}

export function CreateAchievementDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAchievementDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
    };
}

export function CreateAchievementDtoToJSON(json: any): CreateAchievementDto {
    return CreateAchievementDtoToJSONTyped(json, false);
}

export function CreateAchievementDtoToJSONTyped(value?: CreateAchievementDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
    };
}

