/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Auth
 * The NestJS Auth API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateChatParticipantDto
 */
export interface UpdateChatParticipantDto {
    /**
     * Chat participant role
     * @type {string}
     * @memberof UpdateChatParticipantDto
     */
    chatParticipantRole: string;
    /**
     * Is banned
     * @type {boolean}
     * @memberof UpdateChatParticipantDto
     */
    isBanned: boolean;
    /**
     * Is muted
     * @type {boolean}
     * @memberof UpdateChatParticipantDto
     */
    isMuted: boolean;
}

/**
 * Check if a given object implements the UpdateChatParticipantDto interface.
 */
export function instanceOfUpdateChatParticipantDto(value: object): value is UpdateChatParticipantDto {
    if (!('chatParticipantRole' in value) || value['chatParticipantRole'] === undefined) return false;
    if (!('isBanned' in value) || value['isBanned'] === undefined) return false;
    if (!('isMuted' in value) || value['isMuted'] === undefined) return false;
    return true;
}

export function UpdateChatParticipantDtoFromJSON(json: any): UpdateChatParticipantDto {
    return UpdateChatParticipantDtoFromJSONTyped(json, false);
}

export function UpdateChatParticipantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateChatParticipantDto {
    if (json == null) {
        return json;
    }
    return {
        
        'chatParticipantRole': json['chat_participant_role'],
        'isBanned': json['is_banned'],
        'isMuted': json['is_muted'],
    };
}

export function UpdateChatParticipantDtoToJSON(json: any): UpdateChatParticipantDto {
    return UpdateChatParticipantDtoToJSONTyped(json, false);
}

export function UpdateChatParticipantDtoToJSONTyped(value?: UpdateChatParticipantDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chat_participant_role': value['chatParticipantRole'],
        'is_banned': value['isBanned'],
        'is_muted': value['isMuted'],
    };
}

