/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Auth
 * The NestJS Auth API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAchievementDto
 */
export interface UpdateAchievementDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateAchievementDto
     */
    userId: number;
}

/**
 * Check if a given object implements the UpdateAchievementDto interface.
 */
export function instanceOfUpdateAchievementDto(value: object): value is UpdateAchievementDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function UpdateAchievementDtoFromJSON(json: any): UpdateAchievementDto {
    return UpdateAchievementDtoFromJSONTyped(json, false);
}

export function UpdateAchievementDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAchievementDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
    };
}

export function UpdateAchievementDtoToJSON(json: any): UpdateAchievementDto {
    return UpdateAchievementDtoToJSONTyped(json, false);
}

export function UpdateAchievementDtoToJSONTyped(value?: UpdateAchievementDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
    };
}

