/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Auth
 * The NestJS Auth API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {
    /**
     * The nickname of the user.
     * @type {string}
     * @memberof UpdateUserDto
     */
    nickname: string;
    /**
     * The avatar of the user.
     * @type {string}
     * @memberof UpdateUserDto
     */
    avatar: string;
    /**
     * The two factor authentication status of the user.
     * @type {boolean}
     * @memberof UpdateUserDto
     */
    enableTwoFactor: boolean;
}

/**
 * Check if a given object implements the UpdateUserDto interface.
 */
export function instanceOfUpdateUserDto(value: object): value is UpdateUserDto {
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('enableTwoFactor' in value) || value['enableTwoFactor'] === undefined) return false;
    return true;
}

export function UpdateUserDtoFromJSON(json: any): UpdateUserDto {
    return UpdateUserDtoFromJSONTyped(json, false);
}

export function UpdateUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'],
        'avatar': json['avatar'],
        'enableTwoFactor': json['enable_two_factor'],
    };
}

export function UpdateUserDtoToJSON(json: any): UpdateUserDto {
    return UpdateUserDtoToJSONTyped(json, false);
}

export function UpdateUserDtoToJSONTyped(value?: UpdateUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nickname': value['nickname'],
        'avatar': value['avatar'],
        'enable_two_factor': value['enableTwoFactor'],
    };
}

