/* tslint:disable */
/* eslint-disable */
/**
 * NestJS Auth
 * The NestJS Auth API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * The ID of the user.
     * @type {number}
     * @memberof User
     */
    id: number;
    /**
     * The avatar of the user.
     * @type {object}
     * @memberof User
     */
    avatar: object;
    /**
     * The nickname of the user.
     * @type {string}
     * @memberof User
     */
    nickname: string;
    /**
     * The two factor authentication status of the user.
     * @type {boolean}
     * @memberof User
     */
    enableTwoFactor: boolean;
    /**
     * The two factor authentication status of the user.
     * @type {boolean}
     * @memberof User
     */
    isSecondAuthDone: boolean;
    /**
     * The two factor authentication status of the user.
     * @type {number}
     * @memberof User
     */
    secondAuthCode: number;
    /**
     * The email of the user.
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * The ladder level of the user.
     * @type {number}
     * @memberof User
     */
    ladderLevel: number;
    /**
     * The status of the user.
     * @type {string}
     * @memberof User
     */
    userStatus: string;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('enableTwoFactor' in value) || value['enableTwoFactor'] === undefined) return false;
    if (!('isSecondAuthDone' in value) || value['isSecondAuthDone'] === undefined) return false;
    if (!('secondAuthCode' in value) || value['secondAuthCode'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('ladderLevel' in value) || value['ladderLevel'] === undefined) return false;
    if (!('userStatus' in value) || value['userStatus'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'avatar': json['avatar'],
        'nickname': json['nickname'],
        'enableTwoFactor': json['enable_two_factor'],
        'isSecondAuthDone': json['is_second_auth_done'],
        'secondAuthCode': json['second_auth_code'],
        'email': json['email'],
        'ladderLevel': json['ladder_level'],
        'userStatus': json['user_status'],
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'avatar': value['avatar'],
        'nickname': value['nickname'],
        'enable_two_factor': value['enableTwoFactor'],
        'is_second_auth_done': value['isSecondAuthDone'],
        'second_auth_code': value['secondAuthCode'],
        'email': value['email'],
        'ladder_level': value['ladderLevel'],
        'user_status': value['userStatus'],
    };
}

